""" 
Utilty functions for api calls.
""" 

import flask

def forbidden_403():
	""" Check if we should return a 403 
		Usually used on API endpoints """
	context = { 'message': 'Forbidden',
				'status_code': 403}
	return flask.jsonify(**context), 403


CONTRACTIONS = {
    "arent": ["are", "not"],
    "cant": ["can", "not"],
    "couldnt": ["could", "not"],
    "didnt": ["did", "not"],
    "doesnt": ["does", "not"],
    "hadnt": ["had", "not"],
    "hasnt": ["has", "not"],
    "havent": ["have", "not"],
    "hell": ["he", "will"],
    "hes": ["he", "is"],
    "ill": ["i", "will"],
    "im": ["i", "am"],
    "ive": ["i", "have"],
    "isnt": ["is", "not"],
    "shell": ["she", "will"],
    "shes": ["she", "is"],
    "shouldnt": ["should", "not"],
    "thats": ["that", "is"],
    "theres": ["there", "is"],
    "theyd": ["they", "would"],
    "theyll": ["they", "will"],
    "theyre": ["they", "are"],
    "theyve": ["they", "have"],
    "wed": ["we", "would"],
    "were": ["we", "are"],
    "weve": ["we", "have"],
    "werent": ["were", "not"],
    "whatll": ["what", "will"],
    "whatre": ["what", "are"],
    "whats": ["what", "is"],
    "whatve": ["what", "have"],
    "wheres": ["where", "is"],
    "whos": ["who", "is"],
    "wholl": ["who", "will"],
    "whore": ["who", "are"],
    "whove": ["who", "have"],
    "wont": ["will", "not"],
    "wouldnt": ["would", "not"],
    "youd": ["you", "would"],
    "youll": ["you", "will"],
    "youre": ["you", "are"],
    "youve": ["you", "have"]
}

UNIGRAMS = [
	"feel",
	"time",
	"people",
	"life",
	"day",
	"things",
	"work",
	"back",
	"friends",
	"years",
	"told",
	"school",
	"stress",
	"family",
	"job",
	"depression",
	"depressed",
	"stressed",
	"sad",
	"angry",
	"thought",
	"home",
	"fucking",
	"person",
	"upset",
	"cry",
	"crying",
	"wanted",
	"feeling",
	"talk",
	"long",
	"bad",
	"hard",
	"felt",
	"night",
	"insomnia",
	"tired",
	"parents",
	"care",
	"hate",
	"ago",
	"shit",
	"anymore",
	"fuck",
	"point",
	"stop",
	"makes",
	"sleep",
	"hours",
	"asleep",
	"time",
	"sleeping",
	"awake",
	"anxiety",
	"anxious",
	"nervous",
	"morning",
	"melatonin",
	"brain",
	"thinking",
	"thoughts",
	"waking",
	"worry",
	"dont",
	"didnt",
	"doesnt"
]

BIGRAMS = [
	"do not",
	"did not",
	"does not",
	"high school",
	"years ago",
	"i feel",
	"long time",
	"mental health",
	"months ago",
	"social media",
	"feel bad",
	"video games",
	"back home",
	"depression anxiety",
	"full time",
	"dont feel"
	"dont care",
	"dont understand",
	"people dont",
	"dont anymore",
	"spend time",
	"weeks ago",
	"past years",
	"live ive",
	"dont talk",
	"feel guilty",
	"feel sad",
	"ive felt",
	"years ive",
	"suicidal thoughts",
	"hard time",
	"mental illness",
	"feel ive",
	"time ive",
	"ive made",
	"ive lost",
	"fall asleep",
	"hours asleep",
	"falling asleep",
	"4 hours",
	"3 hours",
	"night sleep",
	"wide awake",
	"dont sleep",
	"cant sleep",
	"sleep schedule",
	"feel tired",
	"sleep deprived",
	"couldnt sleep",
	"havent slept",
	"sleep hygine",
	"sleeping pills",
	"back asleep",
	"trouble sleeping",
	"didnt sleep",
	"chronic insomnia",
	"fall back",
	"bed time",
	"good sleep",
	"nights sleep"
]

TRIGRAMS = [
	"do not feel",
	"makes me feel",
	"do not care",
	"made me feel",
	"people do not",
	"do not understand",
	"do not anymore",
	"do not talk",
	"lot of people",
	"i have felt",
	"years i have",
	"feel i have",
	"of my life",
	"time i have",
	"i have made",
	"i have lost",
	"sleep a night",
	"back to sleep",
	"do not sleep",
	"can not sleep",
	"could not sleep",
	"have not slept",
	"slept all day",
	"of the night",
	"did not sleep",
	"lack of sleep",
	"close my eyes",
	"hours of sleep a night",
	"fall back asleep",
	"trouble falling asleep",
	"wake up in the middle of the night",
	"couldnt fall alseep",
	"could not fall asleep",
	"dont feel tired",
	"do not feel tired",
	"good nights sleep",
	"cognitive behavioral therapy",
	"fall asleep faster",
	"unable to fall asleep",
	"feel wide awake",
	"fall asleep easily",
	"falling back asleep",
	"playing video games",
	"full time job",
	"mental health issues",
	"graduated high school",
	"couple of months ago",
	"long time ago",
	"friends from high school",
	"couple weeks ago",
	"doesnt make sense",
	"does not make sense",
	"make ends meet",
	"people dont understand",
	"people do not understand",
	"spend the rest of my life",
	"dont care anymore",
	"do not care anymore",
	"dont give a fuck",
	"do not give a fuck",
	"makes me feel worse",
	"dont care dont",
	"do not care do not",
	"dont feel bad",
	"do not feel bad",
	"past months ive",
	"past months i have"
]